In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import os
import pickle

In [2]:
pd.set_option('display.max_colwidth', None)

In [3]:
loss_path = "../model_outputs/losses/"

In [4]:
loss_path_lists = os.listdir(loss_path)

In [38]:
loss_path_list = []
for i, x in enumerate(loss_path_lists):
    # print(x[:17])
    if x[:17] == "base_test_en_val_":
        loss_path_list.append(x)

In [17]:
# loss_list

In [39]:
for x in loss_path_list:
    if type(x) != str:
        print(type(x))

In [43]:
for i, x in enumerate(loss_path_list):
    print(x[:18])
    if i == 10:
        break

base_test_en_val_y
base_test_en_val_y
base_test_en_val_y
base_test_en_val_y
base_test_en_val_l
base_test_en_val_l
base_test_en_val_y
base_test_en_val_y
base_test_en_val_y
base_test_en_val_y
base_test_en_val_l

In [45]:
loss_arr = []
loss_y_arr = []
for x in loss_path_list:
    if x[:18] == "base_test_en_val_l":
        loss_arr.append(np.load(loss_path + x, allow_pickle=True))
    elif x[:18] == "base_test_en_val_y":
        loss_y_arr.append(np.load(loss_path + x, allow_pickle=True))

In [47]:
for x in loss_arr[:10]:
    print(x[-1])

0.82783216
0.82725036
0.8235343
0.8269599
0.8323551
0.8271525
0.8335643
0.8294798
0.8242342
0.82666683

In [6]:
loss_df = pd.DataFrame({"loss_path": loss_path_lists})

In [7]:
loss_df[(loss_df.loss_path.apply(lambda x: x[:18]) == "base_test_en_val_y") | (loss_df.loss_path.apply(lambda x: x[:18]) == "base_test_en_val_l") ]

                                                           loss_path
2    base_test_en_val_y_lr1.00e-03_wd1.00e-03_drp0.20_bS16_E5_sR0.85
3    base_test_en_val_y_lr1.00e-03_wd1.00e-03_drp0.40_bS64_E5_sR0.95
4    base_test_en_val_y_lr1.00e-03_wd1.00e-04_drp0.30_bS64_E5_sR0.95
5    base_test_en_val_y_lr1.00e-02_wd1.00e-03_drp0.30_bS32_E5_sR0.90
7      base_test_en_val_lr1.00e-03_wd1.00e-03_drp0.20_bS64_E5_sR0.85
..                                                               ...
397    base_test_en_val_lr1.00e-03_wd1.00e-03_drp0.40_bS32_E5_sR0.90
399  base_test_en_val_y_lr1.00e-03_wd1.00e-04_drp0.40_bS16_E5_sR0.85
402  base_test_en_val_y_lr1.00e-02_wd1.00e-04_drp0.30_bS16_E5_sR0.85
404  base_test_en_val_y_lr1.00e-02_wd1.00e-04_drp0.40_bS64_E5_sR0.95
405    base_test_en_val_lr1.00e-02_wd1.00e-03_drp0.20_bS64_E5_sR0.90

[198 rows x 1 columns]

In [8]:
model_name = "base_test_en"

                                                           loss_path
2    base_test_en_val_y_lr1.00e-03_wd1.00e-03_drp0.20_bS16_E5_sR0.85
3    base_test_en_val_y_lr1.00e-03_wd1.00e-03_drp0.40_bS64_E5_sR0.95
4    base_test_en_val_y_lr1.00e-03_wd1.00e-04_drp0.30_bS64_E5_sR0.95
5    base_test_en_val_y_lr1.00e-02_wd1.00e-03_drp0.30_bS32_E5_sR0.90
7      base_test_en_val_lr1.00e-03_wd1.00e-03_drp0.20_bS64_E5_sR0.85
..                                                               ...
397    base_test_en_val_lr1.00e-03_wd1.00e-03_drp0.40_bS32_E5_sR0.90
399  base_test_en_val_y_lr1.00e-03_wd1.00e-04_drp0.40_bS16_E5_sR0.85
402  base_test_en_val_y_lr1.00e-02_wd1.00e-04_drp0.30_bS16_E5_sR0.85
404  base_test_en_val_y_lr1.00e-02_wd1.00e-04_drp0.40_bS64_E5_sR0.95
405    base_test_en_val_lr1.00e-02_wd1.00e-03_drp0.20_bS64_E5_sR0.90

[198 rows x 1 columns]

In [10]:
loss_df["loss_arr"] = [np.load(loss_path + x, allow_pickle=True) for x in loss_df.loss_path]

In [11]:
loss_df["loss_arr_fin"] = [x[-1] for x in loss_df.loss_arr]

In [12]:
loss_df["y_or_not"] = [0 if x[:18] == "base_test_en_val_l" else 1 for x in loss_df.loss_path]

In [72]:
loss_df[loss_df.y_or_not == 0].loss_arr_fin.min(), loss_df[loss_df.y_or_not == 1].loss_arr_fin.min()

(np.float32(0.82327694), np.float32(0.013465761))

In [86]:
best_y_config = loss_df[(loss_df.y_or_not == 1) & (loss_df[(loss_df.y_or_not == 1)].loss_arr_fin == loss_df[(loss_df.y_or_not == 1)].loss_arr_fin.min())].loss_path.iloc[0]

In [87]:
best_config = loss_df[(loss_df.y_or_not == 0) & (loss_df[(loss_df.y_or_not == 0)].loss_arr_fin == loss_df[(loss_df.y_or_not == 0)].loss_arr_fin.min())].loss_path.iloc[0]

In [116]:
corr_df = pd.read_csv("../model_outputs/corrsM2e", sep="\t", names=["path", "corr_9", "mse_9", "corr_11", "mse_11", "corr_13", "mse_13", "corr_15", "mse_15", "best_epoch"])

In [117]:
corr_df[(corr_df.path == ("base_test_en_" + best_config[17:]))]

,path,corr_9,mse_9,corr_11,mse_11,corr_13,mse_13,corr_15,mse_15,best_epoch
14,base_test_en_lr1.00e-03_wd1.00e-04_drp0.20_bS16_E5_sR0.85,-0.071803,81.739396,0.07448,80.585735,-0.052485,81.237163,0.235303,79.739415,3

In [122]:
print(corr_df[(corr_df.path == ("base_test_en_" + best_y_config[19:]))].to_string())

                                                         path    corr_9      mse_9   corr_11     mse_11  corr_13     mse_13   corr_15     mse_15  best_epoch
75  base_test_en_lr1.00e-02_wd1.00e-04_drp0.40_bS16_E5_sR0.95 -0.090876  80.955855  0.055687  78.542221   0.0665  77.797889  0.072069  78.951752           5

In [95]:
best_config

'base_test_en_val_lr1.00e-03_wd1.00e-04_drp0.20_bS16_E5_sR0.85'

In [135]:
corr_df.path[:100].apply(lambda x: x[12:])

0            _lr1.00e-03_wd1.00e-04_drp0.30_bS32_E5_sR0.95
1            _lr1.00e-03_wd1.00e-04_drp0.30_bS32_E5_sR0.90
2            _lr1.00e-03_wd1.00e-04_drp0.30_bS32_E5_sR0.85
3            _lr1.00e-03_wd1.00e-04_drp0.30_bS16_E5_sR0.95
4            _lr1.00e-03_wd1.00e-04_drp0.30_bS16_E5_sR0.90
                              ...
95           _lr1.00e-02_wd1.00e-03_drp0.20_bS16_E5_sR0.85
96           _lr1.00e-02_wd1.00e-03_drp0.20_bS64_E5_sR0.95
97           _lr1.00e-02_wd1.00e-03_drp0.20_bS64_E5_sR0.90
98           _lr1.00e-02_wd1.00e-03_drp0.20_bS64_E5_sR0.85
99    _1by30_lr1.00e-03_wd1.00e-04_drp0.30_bS32_E10_sR0.95
Name: path, Length: 100, dtype: object

In [104]:
"base_test_en_" + best_config[17:]

'base_test_en_lr1.00e-03_wd1.00e-04_drp0.20_bS16_E5_sR0.85'

In [114]:
"base_test_en_" + best_y_config[19:]

'base_test_en_lr1.00e-02_wd1.00e-04_drp0.40_bS16_E5_sR0.95'

In [138]:
best_config[:12] + best_config[16:]

'base_test_en_lr1.00e-03_wd1.00e-04_drp0.20_bS16_E5_sR0.85'

In [141]:
best_y_config[:12] + best_y_config[18:]

'base_test_en_lr1.00e-02_wd1.00e-04_drp0.40_bS16_E5_sR0.95'

In [140]:
best_y_config

'base_test_en_val_y_lr1.00e-02_wd1.00e-04_drp0.40_bS16_E5_sR0.95'